name: single-vm-baseline
version: 1.0.0

description: Basic single VM deployment - proven baseline configuration

# Pattern Configuration
# Specifies which deployment pattern to use
patterns:
  recommended: single-vm
  supported:
    - single-vm

# Network Configuration
# Defines connectivity and access methods for the deployment
network:
  # Primary network for Ansible management connections
  # Options: wireguard, mycelium, public
  main: wireguard
  
  # Inter-node communication network (not applicable for single VM)
  # Options: wireguard, mycelium
  inter_node: wireguard
  
  # Application network mode - defines how services are exposed
  # Options: wireguard-only, mycelium-only, both
  mode: both

# ThreeFold Grid Node Selection
# Specify the node ID from https://dashboard.grid.tf/
nodes:
  vm: 8

# Resource Allocation
# CPU cores, memory (MB), and disk space (GB) for the virtual machine
resources:
  vm:
    cpu: 4
    memory: 8192
    disk: 100
