---
# Minimal common setup for any single VM deployment

# Fix DNS resolution issue on ThreeFold Grid VMs
- name: Configure DNS servers
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 1.1.1.1
      nameserver 8.8.8.8
      nameserver 1.0.0.1
    mode: '0644'

- name: Wait for apt lock to be released
  shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done
  changed_when: false

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  retries: 3
  delay: 10
  register: apt_update
  until: apt_update is succeeded

- name: Install minimal base packages
  apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
    state: present
  retries: 3
  delay: 10
  register: apt_install
  until: apt_install is succeeded

- name: Create TFGrid environment variables
  template:
    src: tfgrid-env.sh.j2
    dest: /etc/profile.d/tfgrid-env.sh
    mode: '0644'
  vars:
    tfgrid_app_name: "{{ tfgrid_app_name }}"
    tfgrid_vm_ip: "{{ tfgrid_vm_ip }}"
    tfgrid_wireguard_ip: "{{ tfgrid_wireguard_ip }}"
    tfgrid_mycelium_ip: "{{ tfgrid_mycelium_ip }}"
