# TFGrid AI Stack - Terraform Infrastructure
# Version: 0.12.0-dev (MVP)

terraform {
  required_version = ">= 1.0"
  required_providers {
    grid = {
      source  = "threefold/grid"
      version = "~> 1.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

# Generate secure passwords and keys
resource "random_password" "gateway_api_key" {
  length  = 32
  special = true
}

resource "random_password" "gitea_admin_password" {
  length  = 16
  special = true
}

resource "random_password" "gitea_db_password" {
  length  = 24
  special = true
}

# Gateway VM - Nginx + Route API + Monitoring
resource "grid_deployment" "gateway" {
  name = "${var.deployment_name}-gateway"

  node_id = var.gateway_node_id != 0 ? var.gateway_node_id : null
  farm_id = var.farm_id != 0 ? var.farm_id : null

  vms {
    name      = "gateway"
    flist     = "https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-22.04.flist"
    cpu       = var.gateway_cpu
    memory    = var.gateway_memory
    rootfs_size = var.gateway_disk
    
    # Public IP if domain specified
    publicip  = var.domain != "" ? true : false
    
    # Environment variables
    env_vars = {
      SSH_KEY    = var.ssh_key
      DOMAIN     = var.domain
      SSL_EMAIL  = var.ssl_email
      API_KEY    = random_password.gateway_api_key.result
    }
    
    # Network configuration
    planetary = true
  }
}

# AI Agent VM - qwen-cli + Project Management
resource "grid_deployment" "ai_agent" {
  name = "${var.deployment_name}-ai-agent"

  node_id = var.ai_agent_node_id != 0 ? var.ai_agent_node_id : null
  farm_id = var.farm_id != 0 ? var.farm_id : null

  vms {
    name      = "ai-agent"
    flist     = "https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-22.04.flist"
    cpu       = var.ai_agent_cpu
    memory    = var.ai_agent_memory
    rootfs_size = var.ai_agent_disk
    
    publicip  = false  # Always private
    
    env_vars = {
      SSH_KEY         = var.ssh_key
      GATEWAY_IP      = grid_deployment.gateway.vms[0].ygg_ip
      GATEWAY_API_KEY = random_password.gateway_api_key.result
      GITEA_IP        = grid_deployment.gitea.vms[0].ygg_ip
    }
    
    planetary = true
  }
  
  depends_on = [grid_deployment.gateway]
}

# Gitea VM - Git Hosting
resource "grid_deployment" "gitea" {
  name = "${var.deployment_name}-gitea"

  node_id = var.gitea_node_id != 0 ? var.gitea_node_id : null
  farm_id = var.farm_id != 0 ? var.farm_id : null

  vms {
    name      = "gitea"
    flist     = "https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-22.04.flist"
    cpu       = var.gitea_cpu
    memory    = var.gitea_memory
    rootfs_size = var.gitea_disk
    
    publicip  = false  # Always private
    
    env_vars = {
      SSH_KEY              = var.ssh_key
      GITEA_ADMIN_USER     = var.gitea_admin_user
      GITEA_ADMIN_PASSWORD = random_password.gitea_admin_password.result
      GITEA_ADMIN_EMAIL    = var.gitea_admin_email
      GITEA_DB_PASSWORD    = random_password.gitea_db_password.result
    }
    
    planetary = true
  }
}

# Local file for SSH configuration
resource "local_file" "ssh_config" {
  filename = "${path.module}/../.ssh_config"
  content = <<-EOT
    # TFGrid AI Stack SSH Configuration
    # Generated by Terraform
    
    Host gateway
      HostName ${grid_deployment.gateway.vms[0].ygg_ip}
      User root
      IdentityFile ${var.ssh_key_path}
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null
    
    Host ai-agent
      HostName ${grid_deployment.ai_agent.vms[0].ygg_ip}
      User root
      IdentityFile ${var.ssh_key_path}
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null
    
    Host gitea
      HostName ${grid_deployment.gitea.vms[0].ygg_ip}
      User root
      IdentityFile ${var.ssh_key_path}
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null
  EOT
  
  file_permission = "0600"
}

# Save credentials to secure file
resource "local_sensitive_file" "credentials" {
  filename = "${path.module}/../.credentials"
  content = <<-EOT
    # TFGrid AI Stack Credentials
    # KEEP THIS FILE SECURE!
    
    GATEWAY_API_KEY=${random_password.gateway_api_key.result}
    GITEA_ADMIN_USER=${var.gitea_admin_user}
    GITEA_ADMIN_PASSWORD=${random_password.gitea_admin_password.result}
    GITEA_DB_PASSWORD=${random_password.gitea_db_password.result}
    
    # Access URLs
    GATEWAY_IP=${grid_deployment.gateway.vms[0].ygg_ip}
    ${var.domain != "" ? "GATEWAY_PUBLIC_URL=https://${var.domain}" : ""}
    AI_AGENT_IP=${grid_deployment.ai_agent.vms[0].ygg_ip}
    GITEA_IP=${grid_deployment.gitea.vms[0].ygg_ip}
  EOT
  
  file_permission = "0600"
}